// Code generated by mockery v2.43.1. DO NOT EDIT.

package uuid

import mock "github.com/stretchr/testify/mock"

// Mock is an autogenerated mock type for the Service type
type Mock struct {
	mock.Mock
}

// New provides a mock function with given fields:
func (_m *Mock) New() UUID {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for New")
	}

	var r0 UUID
	if rf, ok := ret.Get(0).(func() UUID); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(UUID)
	}

	return r0
}

// Parse provides a mock function with given fields: _a0
func (_m *Mock) Parse(_a0 string) (UUID, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (UUID, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) UUID); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(UUID)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMock creates a new instance of Mock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock {
	mock := &Mock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
