inpackage: True
dir: "{{.InterfaceDir}}"
outpkg: "{{.PackageName}}"
with-expecter: False

packages:
  github.com/Peltoche/zapette/internal/service/sysstats:
    interfaces:
      Service:
        config:
          mockname: "Mock{{.InterfaceName}}"
          filename: "{{.InterfaceName | camelcase | firstLower}}_mock.go"
      storage:
        config:
          mockname: "mock{{.InterfaceName | camelcase}}"
          filename: "{{.InterfaceName | camelcase | firstLower}}_mock.go"
  github.com/Peltoche/zapette/internal/service/users:
    interfaces:
      Service:
        config:
          mockname: "Mock{{.InterfaceName}}"
          filename: "{{.InterfaceName | camelcase | firstLower}}_mock.go"
      storage:
        config:
          mockname: "mock{{.InterfaceName | camelcase}}"
          filename: "{{.InterfaceName | camelcase | firstLower}}_mock.go"
  github.com/Peltoche/zapette/internal/service/websessions:
    interfaces:
      Service:
        config:
          mockname: "Mock{{.InterfaceName}}"
          filename: "{{.InterfaceName | camelcase | firstLower}}_mock.go"
      storage:
        config:
          mockname: "mock{{.InterfaceName | camelcase}}"
          filename: "{{.InterfaceName | camelcase | firstLower}}_mock.go"

  # Tools
  github.com/Peltoche/zapette/internal/tools/clock:
    interfaces:
      Clock:
        config:
          mockname: "Mock"
          filename: "mock.go"
  github.com/Peltoche/zapette/internal/tools/uuid:
    interfaces:
      Service:
        config:
          mockname: "Mock"
          filename: "mock.go"
  github.com/Peltoche/zapette/internal/tools/password:
    interfaces:
      Password:
        config:
          mockname: "Mock"
          filename: "mock.go"
  github.com/Peltoche/zapette/internal/tools/response:
    interfaces:
      Writer:
        config:
          mockname: "Mock"
          filename: "mock.go"
  github.com/Peltoche/zapette/internal/web/html:
    interfaces:
      Writer:
        config:
          mockname: "Mock"
          filename: "writer_mock.go"
