// Code generated by mockery v2.43.2. DO NOT EDIT.

package password

import (
	context "context"

	secret "github.com/Peltoche/zapette/internal/tools/secret"
	mock "github.com/stretchr/testify/mock"
)

// Mock is an autogenerated mock type for the Password type
type Mock struct {
	mock.Mock
}

// Compare provides a mock function with given fields: ctx, hash, password
func (_m *Mock) Compare(ctx context.Context, hash secret.Text, password secret.Text) (bool, error) {
	ret := _m.Called(ctx, hash, password)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secret.Text, secret.Text) (bool, error)); ok {
		return rf(ctx, hash, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secret.Text, secret.Text) bool); ok {
		r0 = rf(ctx, hash, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, secret.Text, secret.Text) error); ok {
		r1 = rf(ctx, hash, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encrypt provides a mock function with given fields: ctx, password
func (_m *Mock) Encrypt(ctx context.Context, password secret.Text) (secret.Text, error) {
	ret := _m.Called(ctx, password)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 secret.Text
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, secret.Text) (secret.Text, error)); ok {
		return rf(ctx, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, secret.Text) secret.Text); ok {
		r0 = rf(ctx, password)
	} else {
		r0 = ret.Get(0).(secret.Text)
	}

	if rf, ok := ret.Get(1).(func(context.Context, secret.Text) error); ok {
		r1 = rf(ctx, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMock creates a new instance of Mock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *Mock {
	mock := &Mock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
